development:
  adapter: postgresql
  encoding: unicode
  database: <%= "postgres" %>
  pool: 5
  host: <%= "ror.ceibsxzkmwuv.ap-south-1.rds.amazonaws.com" %>
  
  username: <%= "postgres" %>
  password: <%= "ZhTgXqE1g2n3N46P2now" %>
  port: 5432

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 