development:
  adapter: postgresql
  encoding: unicode
  database: project_management_system_dev
  pool: 5
  host: localhost
  username: postgres
  password: postgres

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 